/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fmlMetro;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.Timer;
import java.lang.String;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author termaat
 */
public class fmlUserInterface extends javax.swing.JFrame {
int xx;
int xy;
int row_num = 0;
int IEmonTracker = 0;     // used to track month backwards and forwards
int IEweekTracker = 7;      // used to track week back and forth
int inTheBeginning = 20000101;
int inTheYear2525 = 25250101;

    SQLite sqlite = new SQLite();
            // created a new object to do db interaction
    
    ArrayList<TransactionShort> ledgerList = new ArrayList<TransactionShort>();
            // ArrayList of the Transaction object
            // the ledger/checkbook of the application
    DefaultTableModel model;
    
    FreakyDate dtx = new FreakyDate();
    
    SimpleDateFormat mdy = new SimpleDateFormat("MM/dd/YYYY");
    
    // date used globally to test against current date
    static java.util.Date today = new java.util.Date();
    String sToday = mdy.format(today.getTime());
    String sDay = new SimpleDateFormat("dd").format(today);
    String sMon = new SimpleDateFormat("MM").format(today);
    String sYr = new SimpleDateFormat("yyyy").format(today);
    String sWk = new SimpleDateFormat("w").format(today);
    String sToday8 = sYr + sMon + sDay;
    int iToday8 = Integer.parseInt(sToday8);
    
    /**
     * Creates new form fmlUserInterface
     */
    public fmlUserInterface() {
        initComponents();
        
        // Fire the app up on the Analytics screen
        pnlCarder.removeAll();
        pnlCarder.repaint();
        pnlCarder.validate();
        
        pnlCarder.add(pnlAnalytics);
        pnlCarder.repaint();
        pnlCarder.validate();
        
        // see of the db is already set up.  0 means there is no table
        int isReady = sqlite.IsAcctSetup();
        if(isReady == 0){
            sqlite.CreateDataBase();
            sqlite.CreateFMLtbl();
            //displayMessage("Enter 1st transaction to set up Acct. balance");
        } 
        
        //set up model for tblLedger
        model = (DefaultTableModel) tblLedger.getModel();
        
        // Center on the screen
        //Toolkit tool = Toolkit.getDefaultToolkit();
        //Dimension dim = new Dimension(tool.getScreenSize());
        //int height = (int) dim.getHeight();
        //int width = (int) dim.getWidth();
        //setSize(width,height);
        //setLocation(width / 2 - getWidth() / 2, height / 2 - getHeight() / 2);
        
        System.out.println("integer Today: " + iToday8);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFML = new javax.swing.JLabel();
        btnAnalytics = new javax.swing.JButton();
        btnIncomeExp = new javax.swing.JButton();
        btnBudget = new javax.swing.JButton();
        bntRegister = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pnlCarder = new javax.swing.JPanel();
        pnlAnalytics = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlLedger = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlReporter = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlBudget = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblBudgReadMe = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pnlIncomeExp = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblIEmaxBills = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblIEmonth = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblIEstartingBal = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lblIEendingBal = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblIEmaxIn = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblIEtoSpend = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        lblIEpercent = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLedger = new javax.swing.JTable(){

            public Component prepareRenderer(TableCellRenderer r, int rw, int col)
            {
                Component c = super.prepareRenderer(r,rw,col);
                c.setBackground(Color.WHITE);
                if(col==5){
                    c.setBackground(Color.PINK);
                }
                return c;
            }
        };
        jPanel13 = new javax.swing.JPanel();
        lblIEreadMe = new javax.swing.JLabel();
        txtIEdate = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIEgoal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtIEamount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIEdescription = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbIEcategory = new javax.swing.JComboBox<>();
        rdoIEincome = new javax.swing.JRadioButton();
        rdoIEexpense = new javax.swing.JRadioButton();
        btnIEadd = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        btnIEupd = new javax.swing.JButton();
        btnIEdel = new javax.swing.JButton();
        chkIErepeat = new javax.swing.JCheckBox();
        lblID = new javax.swing.JLabel();
        rdoIEunplanned = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        lblIEmessage = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnIEbackwards = new javax.swing.JButton();
        btnIEforward = new javax.swing.JButton();
        rdoIEall = new javax.swing.JRadioButton();
        rdoIEmonth = new javax.swing.JRadioButton();
        rdoIEweek = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(700, 615));
        setMinimumSize(new java.awt.Dimension(700, 615));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 615));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 615));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 615));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 112));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        lblFML.setBackground(new java.awt.Color(102, 102, 102));
        lblFML.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblFML.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFML.setText(" .fml");
        lblFML.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblFML.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblFML.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnAnalytics.setBackground(new java.awt.Color(102, 102, 102));
        btnAnalytics.setForeground(new java.awt.Color(102, 102, 102));
        btnAnalytics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bar_black.png"))); // NOI18N
        btnAnalytics.setBorderPainted(false);
        btnAnalytics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalyticsActionPerformed(evt);
            }
        });

        btnIncomeExp.setBackground(new java.awt.Color(102, 102, 102));
        btnIncomeExp.setForeground(new java.awt.Color(102, 102, 102));
        btnIncomeExp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check_black.png"))); // NOI18N
        btnIncomeExp.setToolTipText("");
        btnIncomeExp.setBorderPainted(false);
        btnIncomeExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncomeExpActionPerformed(evt);
            }
        });

        btnBudget.setBackground(new java.awt.Color(102, 102, 102));
        btnBudget.setForeground(new java.awt.Color(102, 102, 102));
        btnBudget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pig_black.png"))); // NOI18N
        btnBudget.setBorderPainted(false);
        btnBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBudgetActionPerformed(evt);
            }
        });

        bntRegister.setBackground(new java.awt.Color(102, 102, 102));
        bntRegister.setForeground(new java.awt.Color(102, 102, 102));
        bntRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/register_black.png"))); // NOI18N
        bntRegister.setBorderPainted(false);
        bntRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegisterActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(102, 102, 102));
        btnExit.setForeground(new java.awt.Color(102, 102, 102));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_black.png"))); // NOI18N
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnExit.setMaximumSize(new java.awt.Dimension(94, 90));
        btnExit.setMinimumSize(new java.awt.Dimension(94, 90));
        btnExit.setPreferredSize(new java.awt.Dimension(94, 90));
        btnExit.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblFML, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAnalytics, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIncomeExp, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bntRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIncomeExp, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnBudget, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(btnAnalytics, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlCarder.setBackground(new java.awt.Color(102, 102, 102));
        pnlCarder.setPreferredSize(new java.awt.Dimension(900, 500));
        pnlCarder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlCarderMouseDragged(evt);
            }
        });
        pnlCarder.setLayout(new java.awt.CardLayout());

        pnlAnalytics.setPreferredSize(new java.awt.Dimension(900, 500));

        jLabel1.setText("Predict the Future and learn from the past");

        javax.swing.GroupLayout pnlAnalyticsLayout = new javax.swing.GroupLayout(pnlAnalytics);
        pnlAnalytics.setLayout(pnlAnalyticsLayout);
        pnlAnalyticsLayout.setHorizontalGroup(
            pnlAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnalyticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(927, Short.MAX_VALUE))
        );
        pnlAnalyticsLayout.setVerticalGroup(
            pnlAnalyticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAnalyticsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        pnlCarder.add(pnlAnalytics, "card2");

        pnlLedger.setPreferredSize(new java.awt.Dimension(900, 496));

        jLabel4.setText("Balance that Account!");

        javax.swing.GroupLayout pnlLedgerLayout = new javax.swing.GroupLayout(pnlLedger);
        pnlLedger.setLayout(pnlLedgerLayout);
        pnlLedgerLayout.setHorizontalGroup(
            pnlLedgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLedgerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(1053, Short.MAX_VALUE))
        );
        pnlLedgerLayout.setVerticalGroup(
            pnlLedgerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLedgerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        pnlCarder.add(pnlLedger, "card2");

        pnlReporter.setPreferredSize(new java.awt.Dimension(900, 496));
        pnlReporter.setRequestFocusEnabled(false);

        jLabel5.setText("Reserved for future html reporting");

        javax.swing.GroupLayout pnlReporterLayout = new javax.swing.GroupLayout(pnlReporter);
        pnlReporter.setLayout(pnlReporterLayout);
        pnlReporterLayout.setHorizontalGroup(
            pnlReporterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(974, Short.MAX_VALUE))
        );
        pnlReporterLayout.setVerticalGroup(
            pnlReporterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReporterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        pnlCarder.add(pnlReporter, "card2");

        pnlBudget.setBackground(new java.awt.Color(102, 102, 102));
        pnlBudget.setPreferredSize(new java.awt.Dimension(900, 496));

        jPanel7.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Budgeting your spending weekly is a key tenant to improving your life...");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));

        lblBudgReadMe.setText("For Income and Expenes we will look at life ");
        lblBudgReadMe.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBudgReadMe.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jFormattedTextField1.setText("12/31/2525");

        jLabel3.setText(".date");

        jLabel9.setText(".enter the first date for this item");

        jLabel10.setText(".frequency");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lblBudgReadMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lblBudgReadMe, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(0, 208, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(102, 102, 102));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("...Welcome to fml Finance message center");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlBudgetLayout = new javax.swing.GroupLayout(pnlBudget);
        pnlBudget.setLayout(pnlBudgetLayout);
        pnlBudgetLayout.setHorizontalGroup(
            pnlBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBudgetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBudgetLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator2)
        );
        pnlBudgetLayout.setVerticalGroup(
            pnlBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBudgetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBudgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlCarder.add(pnlBudget, "card2");

        pnlIncomeExp.setBackground(new java.awt.Color(102, 102, 102));
        pnlIncomeExp.setPreferredSize(new java.awt.Dimension(900, 496));

        jPanel11.setBackground(new java.awt.Color(102, 102, 102));

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("     ...A place to add income and expense items that make up your life");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(102, 102, 102));
        jPanel12.setPreferredSize(new java.awt.Dimension(344, 400));

        lblIEmaxBills.setBackground(java.awt.Color.pink);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText(" . month");

        lblIEmonth.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        lblIEmonth.setText("February");

        jLabel20.setText(" . starting balance");
        jLabel20.setToolTipText("");

        lblIEstartingBal.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblIEstartingBal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIEstartingBal.setText("$1250");

        jLabel23.setText(" . ending balance");

        lblIEendingBal.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblIEendingBal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIEendingBal.setText("$950");

        jLabel25.setText(" . total income this month");

        lblIEmaxIn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblIEmaxIn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIEmaxIn.setText("$3500");
        lblIEmaxIn.setToolTipText("");

        jLabel27.setText(" . total bills this month");

        jLabel28.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("$2650");

        jLabel29.setText(" . money to spend and save");

        lblIEtoSpend.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblIEtoSpend.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIEtoSpend.setText("$850");

        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Bill run down");

        jLabel32.setText("bill 1");

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("$830");

        jLabel34.setText("bill 2");

        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("$135");

        jLabel36.setText("bill 3");

        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("$89");

        jLabel38.setText("bill 4");

        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("$43");

        jLabel40.setText(" . % of income used for bills");

        lblIEpercent.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblIEpercent.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIEpercent.setText("76%");

        javax.swing.GroupLayout lblIEmaxBillsLayout = new javax.swing.GroupLayout(lblIEmaxBills);
        lblIEmaxBills.setLayout(lblIEmaxBillsLayout);
        lblIEmaxBillsLayout.setHorizontalGroup(
            lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                .addGroup(lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIEendingBal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIEmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIEstartingBal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblIEmaxIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIEtoSpend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                    .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIEpercent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lblIEmaxBillsLayout.setVerticalGroup(
            lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblIEmaxBillsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblIEmonth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lblIEstartingBal))
                .addGap(12, 12, 12)
                .addGroup(lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblIEendingBal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIEmaxIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIEtoSpend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIEpercent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lblIEmaxBillsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));

        tblLedger.setBackground(new java.awt.Color(204, 204, 204));
        tblLedger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "date", "name", "catgory", "amt", "bal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLedger.setGridColor(new java.awt.Color(153, 153, 153));
        tblLedger.getTableHeader().setReorderingAllowed(false);
        tblLedger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLedgerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLedger);
        if (tblLedger.getColumnModel().getColumnCount() > 0) {
            tblLedger.getColumnModel().getColumn(0).setResizable(false);
            tblLedger.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblLedger.getColumnModel().getColumn(1).setResizable(false);
            tblLedger.getColumnModel().getColumn(1).setPreferredWidth(40);
            tblLedger.getColumnModel().getColumn(2).setResizable(false);
            tblLedger.getColumnModel().getColumn(2).setPreferredWidth(65);
            tblLedger.getColumnModel().getColumn(3).setResizable(false);
            tblLedger.getColumnModel().getColumn(3).setPreferredWidth(60);
            tblLedger.getColumnModel().getColumn(4).setResizable(false);
            tblLedger.getColumnModel().getColumn(4).setPreferredWidth(40);
            tblLedger.getColumnModel().getColumn(5).setResizable(false);
            tblLedger.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(lblIEmaxBills, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                    .addComponent(lblIEmaxBills, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(102, 102, 102));
        jPanel13.setPreferredSize(new java.awt.Dimension(344, 400));

        lblIEreadMe.setText("For Income and Expenes we will look at life ");
        lblIEreadMe.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblIEreadMe.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        txtIEdate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yy"))));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText(" . date");

        txtIEgoal.setText("123456");
        txtIEgoal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIEgoalKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText(" . goal");

        txtIEamount.setText("123456");
        txtIEamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIEamountKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIEamountKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel12.setText(" . amount");

        jLabel15.setText(". first occurance");

        jLabel18.setText(" . the usual amount");

        jLabel19.setText(". have a goal?");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel13.setText(" . description");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel14.setText(" . category");

        cmbIEcategory.setEditable(true);
        cmbIEcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "income", "expense" }));

        rdoIEincome.setText("income");
        rdoIEincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIEincomeActionPerformed(evt);
            }
        });

        rdoIEexpense.setText("bill");
        rdoIEexpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIEexpenseActionPerformed(evt);
            }
        });

        btnIEadd.setText("add");
        btnIEadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEaddActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel22.setText(" . type");

        btnIEupd.setText("upd");
        btnIEupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEupdActionPerformed(evt);
            }
        });

        btnIEdel.setText("del");
        btnIEdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEdelActionPerformed(evt);
            }
        });

        chkIErepeat.setText(". repeat");
        chkIErepeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIErepeatActionPerformed(evt);
            }
        });

        lblID.setText("aaa");

        rdoIEunplanned.setText("unplanned");
        rdoIEunplanned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIEunplannedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIEreadMe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(txtIEdate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(txtIEamount, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbIEcategory, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btnIEdel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIEupd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIEadd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkIErepeat))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIEdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtIEgoal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoIEexpense, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoIEincome)
                                        .addGap(8, 8, 8)
                                        .addComponent(rdoIEunplanned)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(lblIEreadMe, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIEdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtIEamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(10, 10, 10)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtIEgoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtIEdescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmbIEcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(rdoIEexpense)
                    .addComponent(rdoIEincome)
                    .addComponent(rdoIEunplanned))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIEdel)
                    .addComponent(btnIEupd)
                    .addComponent(btnIEadd)
                    .addComponent(chkIErepeat))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel14.setBackground(new java.awt.Color(102, 102, 102));

        lblIEmessage.setBackground(new java.awt.Color(102, 102, 102));
        lblIEmessage.setForeground(new java.awt.Color(255, 255, 255));
        lblIEmessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIEmessage.setText("...Welcome to fml Finance message center");
        lblIEmessage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIEmessage, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(lblIEmessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        btnIEbackwards.setText("<");
        btnIEbackwards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEbackwardsActionPerformed(evt);
            }
        });

        btnIEforward.setText(">");
        btnIEforward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIEforwardActionPerformed(evt);
            }
        });

        rdoIEall.setText("all");
        rdoIEall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIEallActionPerformed(evt);
            }
        });

        rdoIEmonth.setText("month");
        rdoIEmonth.setToolTipText("");
        rdoIEmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIEmonthActionPerformed(evt);
            }
        });

        rdoIEweek.setText("week");
        rdoIEweek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIEweekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(btnIEbackwards, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoIEall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoIEmonth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoIEweek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIEforward, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIEbackwards)
                    .addComponent(btnIEforward)
                    .addComponent(rdoIEall)
                    .addComponent(rdoIEmonth)
                    .addComponent(rdoIEweek))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlIncomeExpLayout = new javax.swing.GroupLayout(pnlIncomeExp);
        pnlIncomeExp.setLayout(pnlIncomeExpLayout);
        pnlIncomeExpLayout.setHorizontalGroup(
            pnlIncomeExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlIncomeExpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIncomeExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIncomeExpLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlIncomeExpLayout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator3)
        );
        pnlIncomeExpLayout.setVerticalGroup(
            pnlIncomeExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIncomeExpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIncomeExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, 396, 396, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIncomeExpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCarder.add(pnlIncomeExp, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCarder, javax.swing.GroupLayout.PREFERRED_SIZE, 1195, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlCarder, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
        
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        setOpacity((float)0.7);
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        // TODO add your handling code here:
        setOpacity((float)1.0);
    }//GEN-LAST:event_jPanel2MouseReleased

    private void pnlCarderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCarderMouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_pnlCarderMouseDragged

    private void btnAnalyticsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalyticsActionPerformed
        // Remove existing panel(s)
        pnlCarder.removeAll();;
        pnlCarder.repaint();;
        pnlCarder.validate();;
        
        // add new pane based on selection
        pnlCarder.add(pnlAnalytics);
        pnlCarder.repaint();
        pnlCarder.validate();
        
    }//GEN-LAST:event_btnAnalyticsActionPerformed

    private void btnIncomeExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncomeExpActionPerformed
        // Remove existing panel(s)
        pnlCarder.removeAll();;
        pnlCarder.repaint();;
        pnlCarder.validate();;
        
        // add new pane based on selection
        pnlCarder.add(pnlIncomeExp);
        pnlCarder.repaint();
        pnlCarder.validate();
        ClearIEdataEntry();
        //jLabel16.setVisible(false);
        String html = "<html>Income and Expenses are tracked monthly. This is the" + 
                      "<br>first step to coming to terms with your finances. Start by" +
                      "<br>adding all of the bills you have as well as income. What's" +
                      "<br>left is what we will work with on the budget section. Don't" +
                      "<br>forget - lowering your expenses is like giving yourself a" +
                      "<br>RAISE and doesn't cost another little piece of your soul.";
        lblIEreadMe.setText(html);
        
        IEmonTracker = 0;
        int ieFOM = dtx.getIntFOM(0);
        int ieEOM = dtx.getIntEOM(0);
        //System.out.println("month button beg " + ieFOM);
        //System.out.println("month button end " + ieEOM);
        
        ListTransactionsByDate(ieFOM, ieEOM);
        rdoIEmonth.setSelected(true);
        RefreshAnalytics(ieFOM, ieEOM);

        
        //ListTransactions();
        //rdoIEall.setSelected(true);
    }//GEN-LAST:event_btnIncomeExpActionPerformed

    private void btnBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBudgetActionPerformed
        // Remove existing panel(s)
        pnlCarder.removeAll();;
        pnlCarder.repaint();;
        pnlCarder.validate();;
        
        // add new pane based on selection
        pnlCarder.add(pnlBudget);
        pnlCarder.repaint();
        pnlCarder.validate();
        
        String html = "<html>Of course bills and income are the core of our finances," + 
                      "<br>but it's the $ you spend weekly that determines your" +
                      "<br>success. And, don't forget to SAVE. Everyweek put a little" +
                      "<br>aside for yourself and your goal of not being a slave to" +
                      "<br>the man. We work so hard to get $, but ignore the fact that" +
                      "<br>when we pay off a debt or lower an expense we are raising our" +
                      "<br>income, control, freedom, self-esteem. Yes it's that powerful";
        lblBudgReadMe.setText(html);
    }//GEN-LAST:event_btnBudgetActionPerformed

    private void bntRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegisterActionPerformed
        // Remove existing panel(s)
        pnlCarder.removeAll();;
        pnlCarder.repaint();;
        pnlCarder.validate();;
        
        // add new pane based on selection
        pnlCarder.add(pnlLedger);
        pnlCarder.repaint();
        pnlCarder.validate();
    }//GEN-LAST:event_bntRegisterActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Close the Application
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed
    
    // since the add and update do the same thing it make sense to use 1 code base
    private void AddUpdateTransaction(String action, int id){
        Date jDate = null;
        String sDate8, day, mon, yr, wk, cat, name;
        String type = "";
        String frq = "notused";
        String ieDate = txtIEdate.getText();
        int iDate8 = 0; int amt = 0; int budg = 0;
        int modifier = 0;
        
        // date is good to use
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yy");
        try
        {
            jDate = sdf.parse(ieDate);
        }
        catch(ParseException e) {
            DisplayIEmessage("Enter date like 04/15/18 and not some " +
                                                    "other bogus format");
            return;
        }
            
        day = new SimpleDateFormat("dd").format(jDate);
        mon = new SimpleDateFormat("MM").format(jDate);
        yr = new SimpleDateFormat("yyyy").format(jDate);
        wk = new SimpleDateFormat("w").format(jDate);
        sDate8 = yr + mon + day;
        iDate8 = Integer.parseInt(sDate8);
            //System.out.println("day " + day);
            //System.out.println("mon " + mon);
            //System.out.println("year " + yr);
            //System.out.println("sDate8 " + sDate8);
            //System.out.println("week " + wk);

        // is today sunday?  if it is we need to subtract a week since our
        // program wants to start on Monday as the first day of the week
        int intwk = Integer.valueOf(wk);
        if(dtx.IsSunday(jDate)){
            if(intwk==1){
                intwk=52;
                wk = String.valueOf(intwk);
            }
            else{
                intwk--;
                wk = String.valueOf(intwk);
            }
        }
        
        String ieDEvalidate = ValidateIEdataEntry();
        if(!ieDEvalidate.equals("FAIL")){
            // data entry is good to use
            //frq = cmbIEfreq.getSelectedItem().toString();
            cat = cmbIEcategory.getSelectedItem().toString();
            name = txtIEdescription.getText();
            amt = Integer.valueOf(txtIEamount.getText());
            budg = Integer.valueOf(txtIEgoal.getText());
            
            if(rdoIEincome.isSelected()){
                type = "income";
            }
            if(rdoIEexpense.isSelected()){
                type = "bill";
                amt = amt*-1;
                budg = budg*-1;
            }
            if(rdoIEunplanned.isSelected()){
                type = "unplanned";
                amt = amt*-1;
                budg = budg*-1;
            }
            
            if(action.equals("ADD")){
                int xID = sqlite.AddTransaction(iDate8, day, mon, yr, wk, 
                                            type, frq, cat, name, amt, budg);
            }
            else {
                sqlite.UpdateTran(id, iDate8, cat, name, type, amt, budg);
            }
                
        }
        else {
            DisplayIEmessage("Check your data entry cause something ain't right");
            return;
        }
        
        
        
    }
    // adds income and expenses
    private void btnIEaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEaddActionPerformed
        AddUpdateTransaction("ADD", 0);
        
        if (!chkIErepeat.isSelected()){
            ClearIEdataEntry();
        }
        else{
            txtIEdate.setText("");
        }
            
        ListTransactions();
    }//GEN-LAST:event_btnIEaddActionPerformed
    
    private void ListTransactionsByDate(int dateStart, int dateEnd){
      
      //remove all the rows currently in the table
      model.setRowCount(0);
      
      ArrayList<TransactionShort> ledgerList = sqlite.getTransactionsByDate(dateStart, dateEnd);
      Object rowData[] = new Object[6];
      for(int i = 0; i < ledgerList.size(); i++)
      {
        rowData[0] = ledgerList.get(i).getID();
        
        String sdate8 = String.valueOf(ledgerList.get(i).getDate());
        String smon = sdate8.substring(4, 6);
        String sday = sdate8.substring(6);
        String shortDate = smon + "/" + sday;
        
        rowData[1] = shortDate;
        rowData[2] = ledgerList.get(i).getName();
        rowData[3] = ledgerList.get(i).getCategory();
        rowData[4] = ledgerList.get(i).getAmount();
        rowData[5] = ledgerList.get(i).gettBalance();
        
        model.addRow(rowData); 
      }
      tblLedger.getColumnModel().getColumn(0).setWidth(0);
      tblLedger.getColumnModel().getColumn(0).setMinWidth(0);
      tblLedger.getColumnModel().getColumn(0).setMaxWidth(0); 
    }
    
    private void RefreshAnalytics(int dateStart, int dateEnd){
        
        int row = (tblLedger.getRowCount() -1);
        if(row>-1){
           //Analytics balances
           lblIEendingBal.setText("$" + String.valueOf(model.getValueAt(row,5)));
           lblIEstartingBal.setText("$" + String.valueOf(model.getValueAt(0,5)));
        }
        
        lblIEmonth.setText(dtx.getMonthDesc(IEmonTracker));
        
    }
    private void ListTransactions(){
      
      //remove all the rows currently in the table
      model.setRowCount(0);
      
      ArrayList<TransactionShort> ledgerList = sqlite.getAllObjects();
      Object rowData[] = new Object[6];
      for(int i = 0; i < ledgerList.size(); i++)
      {
        rowData[0] = ledgerList.get(i).getID();
        
        String sdate8 = String.valueOf(ledgerList.get(i).getDate());
        String smon = sdate8.substring(4, 6);
        String sday = sdate8.substring(6);
        String shortDate = smon + "/" + sday;
        
        rowData[1] = shortDate;
        //rowData[1] = ledgerList.get(i).getDate();
        rowData[2] = ledgerList.get(i).getName();
        rowData[3] = ledgerList.get(i).getCategory();
        rowData[4] = ledgerList.get(i).getAmount();
        rowData[5] = ledgerList.get(i).gettBalance();
        
        model.addRow(rowData); 
      }
      tblLedger.getColumnModel().getColumn(0).setWidth(0);
      tblLedger.getColumnModel().getColumn(0).setMinWidth(0);
      tblLedger.getColumnModel().getColumn(0).setMaxWidth(0); 
      //DisplayCatSummary();
    }
    
    public static String leftPad(int n, int padding) {
        return String.format("%0" + padding + "d", n);
    }
    
    private void txtIEamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIEamountKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIEamountKeyPressed

    private void txtIEamountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIEamountKeyTyped
        // Code to only allow integers in amount fields
        char vchar = evt.getKeyChar();
        if(!Character.isDigit(vchar)
            || (vchar == KeyEvent.VK_BACKSPACE)
            || (vchar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtIEamountKeyTyped

    private void txtIEgoalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIEgoalKeyTyped
        // Code to only allow integers in amount fields
        char vchar = evt.getKeyChar();
        if(!Character.isDigit(vchar)
            || (vchar == KeyEvent.VK_BACKSPACE)
            || (vchar == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_txtIEgoalKeyTyped

    private void rdoIEexpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIEexpenseActionPerformed
        rdoIEincome.setSelected(false);
        rdoIEunplanned.setSelected(false);
    }//GEN-LAST:event_rdoIEexpenseActionPerformed

    private void rdoIEincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIEincomeActionPerformed
        rdoIEexpense.setSelected(false);
        rdoIEunplanned.setSelected(false);
    }//GEN-LAST:event_rdoIEincomeActionPerformed

    private void chkIErepeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIErepeatActionPerformed
        if(!chkIErepeat.isSelected()){
            ClearIEdataEntry();
        }
    }//GEN-LAST:event_chkIErepeatActionPerformed

    private void tblLedgerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLedgerMouseClicked
        // TODO add your handling code here:
        
        int i = tblLedger.getSelectedRow();
        row_num = tblLedger.getSelectedRow();
        
        String ids = String.valueOf(model.getValueAt(i, 0));
        int id = Integer.valueOf(ids);
        //rec_id = Integer.valueOf(ids);
        
        TransactionLong xTran = sqlite.GetTransaction(id);
        
        lblID.setText(String.valueOf(xTran.getID()));
        
        String s_amt = String.valueOf(xTran.getAmount());
        int amt = Integer.valueOf(s_amt);
        if(amt < 0){
            amt = amt * -1;
            rdoIEexpense.setSelected(true);
        }
        else{
            rdoIEincome.setSelected(true);
        }
        txtIEamount.setText(String.valueOf(amt));
        
        String b_amt = String.valueOf(xTran.getBudget());
        int budget_amt = Integer.valueOf(b_amt);
        if(budget_amt < 0){
            budget_amt = budget_amt * -1;
        }
        txtIEgoal.setText(String.valueOf(budget_amt));

        txtIEdescription.setText(xTran.getName());
        cmbIEcategory.setSelectedItem(xTran.getCategory());
        
        int yr_i = Integer.valueOf(xTran.getYr()) - 2000;
        String yr_s = String.valueOf(yr_i);
        String mdyDate = xTran.getMon()+ "/" + xTran.getDay() + "/" + yr_s;
        txtIEdate.setText(mdyDate);
               
    }//GEN-LAST:event_tblLedgerMouseClicked

    //RODT - need to get ID to update transaction
    private void btnIEdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEdelActionPerformed
        //make sure they have the DE screen filled befor deleting
        if(!lblID.getText().equals("aaa")){
            int delID = Integer.valueOf(lblID.getText());
            sqlite.deleteTran(delID);
            lblID.setText("");
            this.ClearIEdataEntry();
            ListTransactions();
        }
        else{
            DisplayIEmessage("Select something to delete instead of trying to break the program");
        }
     
    }//GEN-LAST:event_btnIEdelActionPerformed

    private void btnIEupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEupdActionPerformed
        if(!lblID.getText().equals("aaa")){
            int updID = Integer.valueOf(lblID.getText());
            AddUpdateTransaction("UPD", updID);
            lblID.setText("");
            this.ClearIEdataEntry();
            ListTransactions();
        }
        else{
            DisplayIEmessage("Somehow you botched the update data, please correct");
        }
        
    }//GEN-LAST:event_btnIEupdActionPerformed

    private void btnIEforwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEforwardActionPerformed
        if(rdoIEmonth.isSelected()){
            IEmonTracker++;
            int ieFOM = dtx.getIntFOM(IEmonTracker);
            int ieEOM = dtx.getIntEOM(IEmonTracker);
            System.out.println("mon forward beg " + ieFOM);
            System.out.println("mon forward end " + ieEOM);
            ListTransactionsByDate(ieFOM, ieEOM);
            RefreshAnalytics(ieFOM, ieEOM);
        }
        if(rdoIEweek.isSelected()){
            IEweekTracker = IEweekTracker+7;
            int ieFOW = dtx.getIntFOW(IEweekTracker);
            int ieEOW = dtx.getIntEOW(IEweekTracker);
            System.out.println("week forward beg " + ieFOW);
            System.out.println("week forward end " + ieEOW);
            ListTransactionsByDate(ieFOW, ieEOW);
            RefreshAnalytics(ieFOW, ieEOW);
        }
    }//GEN-LAST:event_btnIEforwardActionPerformed

    private void btnIEbackwardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIEbackwardsActionPerformed
        if(rdoIEmonth.isSelected()){
            IEmonTracker--;
            int ieFOM = dtx.getIntFOM(IEmonTracker);
            int ieEOM = dtx.getIntEOM(IEmonTracker);
            System.out.println("mon backward beg " + ieFOM);
            System.out.println("mon backward end " + ieEOM);
            ListTransactionsByDate(ieFOM, ieEOM); 
            RefreshAnalytics(ieFOM, ieEOM);
        }
        if (rdoIEweek.isSelected()){
            IEweekTracker = IEweekTracker-7;
            int ieFOW = dtx.getIntFOW(IEweekTracker);
            int ieEOW = dtx.getIntEOW(IEweekTracker);
            System.out.println("week backward beg " + ieFOW);
            System.out.println("week backward end " + ieEOW);
            ListTransactionsByDate(ieFOW, ieEOW);
            RefreshAnalytics(ieFOW, ieEOW);
        }
    }//GEN-LAST:event_btnIEbackwardsActionPerformed

    private void rdoIEmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIEmonthActionPerformed
        rdoIEweek.setSelected(false);
        rdoIEall.setSelected(false);
        IEmonTracker = 0;
        int ieFOM = dtx.getIntFOM(0);
        int ieEOM = dtx.getIntEOM(0);
        System.out.println("month button beg " + ieFOM);
        System.out.println("month button end " + ieEOM);
        
        ListTransactionsByDate(ieFOM, ieEOM);
        RefreshAnalytics(ieFOM, ieEOM);
    }//GEN-LAST:event_rdoIEmonthActionPerformed

    private void rdoIEweekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIEweekActionPerformed
        IEweekTracker = 7;
        rdoIEmonth.setSelected(false);
        rdoIEall.setSelected(false);
        int ieFOW = dtx.getIntFOW(IEweekTracker);
        int ieEOW = dtx.getIntEOW(IEweekTracker);
        System.out.println("month button beg " + ieFOW);
        System.out.println("month button end " + ieEOW);
        
        ListTransactionsByDate(ieFOW, ieEOW);
        RefreshAnalytics(ieFOW, ieEOW);
    }//GEN-LAST:event_rdoIEweekActionPerformed

    private void rdoIEallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIEallActionPerformed
        rdoIEweek.setSelected(false);
        rdoIEmonth.setSelected(false);
        IEmonTracker = 0;
        IEweekTracker = 7;
        ListTransactionsByDate(inTheBeginning, inTheYear2525);
        RefreshAnalytics(inTheBeginning, inTheYear2525);
    }//GEN-LAST:event_rdoIEallActionPerformed

    private void rdoIEunplannedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIEunplannedActionPerformed
        rdoIEexpense.setSelected(false);
        rdoIEincome.setSelected(false);
    }//GEN-LAST:event_rdoIEunplannedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmlUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmlUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmlUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmlUserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmlUserInterface().setVisible(true);
            }
        });
    }
    
    // Income and Expense panel
    
    // Clears the data entry area of Income and Expense panel
    private void ClearIEdataEntry(){
        txtIEdate.setText("");
        //cmbIEfreq.setSelectedIndex(-1);
        txtIEamount.setText("");
        txtIEgoal.setText("");
        txtIEdescription.setText("");
        cmbIEcategory.setSelectedIndex(-1);
        rdoIEincome.setSelected(false);
        rdoIEexpense.setSelected(false);
        rdoIEunplanned.setSelected(false);
    }
    
    // Displays data entry error messages on Income and Expense panel
    private void DisplayIEmessage(String message){
        lblIEmessage.setText(message);
        
        Timer t = new Timer(2000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                lblIEmessage.setText(null);
            }
        });
        t.setRepeats(false);
        t.start();
    }
    
    // validates the DE part of the form and returns PASS or FAIL to caller
    private String ValidateIEdataEntry(){
        //final String catTest = cmbIEcategory.getSelectedItem().toString().trim();
        //final String freqTest = cmbIEfreq.getSelectedItem().toString().trim();
        if(txtIEamount.getText().equals("")){
            return "FAIL";}
        else if(txtIEdescription.getText().equals("")){
            return "FAIL";}
        else if(cmbIEcategory.getSelectedItem() == null
                || cmbIEcategory.getSelectedItem().toString().isEmpty()){
            return "FAIL";
        } else if(!(rdoIEincome.isSelected() || rdoIEexpense.isSelected() ||
                rdoIEunplanned.isSelected())) {
            return "FAIL";
        //} else if (cmbIEfreq.getSelectedItem() == null 
        //        || cmbIEfreq.getSelectedItem().toString().isEmpty()){
        //    return "FAIL";
        }else{
            return "PASS";}
    }
    
    //  RODT - format date to DE format
    // takes the integer date YYYYMMDD and returns MM/DD/YY for the DE screen
    private String FormatDate(String ymddate){
        java.util.Date date;
        String mdydate = "";
        
        SimpleDateFormat mdyFormattedDate = new SimpleDateFormat("MM/dd/yy");
        SimpleDateFormat ymdFormattedDate = new SimpleDateFormat("yyyyMMdd");
       
        try
        {
          date = ymdFormattedDate.parse(ymddate);
          mdydate = mdyFormattedDate.format(date);          
        }
          catch(ParseException e) {
          DisplayIEmessage("Enter date like 04/15/18 " +
                        " and not some other bogus format");
          ClearIEdataEntry();
        }

        return mdydate;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntRegister;
    private javax.swing.JButton btnAnalytics;
    private javax.swing.JButton btnBudget;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnIEadd;
    private javax.swing.JButton btnIEbackwards;
    private javax.swing.JButton btnIEdel;
    private javax.swing.JButton btnIEforward;
    private javax.swing.JButton btnIEupd;
    private javax.swing.JButton btnIncomeExp;
    private javax.swing.JCheckBox chkIErepeat;
    private javax.swing.JComboBox<String> cmbIEcategory;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBudgReadMe;
    private javax.swing.JLabel lblFML;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIEendingBal;
    private javax.swing.JPanel lblIEmaxBills;
    private javax.swing.JLabel lblIEmaxIn;
    private javax.swing.JLabel lblIEmessage;
    private javax.swing.JLabel lblIEmonth;
    private javax.swing.JLabel lblIEpercent;
    private javax.swing.JLabel lblIEreadMe;
    private javax.swing.JLabel lblIEstartingBal;
    private javax.swing.JLabel lblIEtoSpend;
    private javax.swing.JPanel pnlAnalytics;
    private javax.swing.JPanel pnlBudget;
    private javax.swing.JPanel pnlCarder;
    private javax.swing.JPanel pnlIncomeExp;
    private javax.swing.JPanel pnlLedger;
    private javax.swing.JPanel pnlReporter;
    private javax.swing.JRadioButton rdoIEall;
    private javax.swing.JRadioButton rdoIEexpense;
    private javax.swing.JRadioButton rdoIEincome;
    private javax.swing.JRadioButton rdoIEmonth;
    private javax.swing.JRadioButton rdoIEunplanned;
    private javax.swing.JRadioButton rdoIEweek;
    private javax.swing.JTable tblLedger;
    private javax.swing.JTextField txtIEamount;
    private javax.swing.JFormattedTextField txtIEdate;
    private javax.swing.JTextField txtIEdescription;
    private javax.swing.JTextField txtIEgoal;
    // End of variables declaration//GEN-END:variables
}
