/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fmlMetro;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author termaat
 */

public class PrintSummary extends javax.swing.JFrame {

    SQLite sqlx = new SQLite();   // database object
    SimpleDateFormat mdy = new SimpleDateFormat("MM/dd/YYYY");
    FreakyDate dty = new FreakyDate();
    DefaultTableModel printModel;

    
    /**
     * Creates new form PrintSummary
     */
    public PrintSummary() {
        initComponents();
        
        //set up the model for the checkbook register
        printModel = (DefaultTableModel) tblPrinter.getModel();   
        
        printModel.setRowCount(0);
      
      ArrayList<TransactionLong> theLedger = sqlx.PrintCheckbook(20180101, 20180131);
      Object rowData[] = new Object[6];
      String newDate = "";
      String oldDate = "";
      String newWeek = "";
      String oldWeek = "";
      
      for(int i = 0; i < theLedger.size(); i++)
      {
        if(i==0){
            rowData[0] = "January";
            rowData[1] = "";
            rowData[2] = "";
            rowData[3] = "Starting Balance";
            rowData[4] = "";
            int amt = theLedger.get(i).getAmount();
            if(amt<0){ amt= amt*-1;}
            rowData[5] = amt + theLedger.get(i).getBalance();
            printModel.addRow(rowData);
        }
        
        //week
        newWeek = theLedger.get(i).getWk();
        if(newWeek.equals(oldWeek)){
            rowData[0] = "";
        } else {
            rowData[0] = newWeek;
            oldWeek = newWeek;
        }
        
        //date
        String sdate8 = String.valueOf(theLedger.get(i).getDate());
        String smon = sdate8.substring(4, 6);
        String sday = sdate8.substring(6);
        String shortDate = smon + "/" + sday;
        newDate = shortDate;
        
        if(theLedger.get(i).getType().equals("4")){
            rowData[1] = "";
        } else {
            rowData[1] = shortDate;
        }
        
//        if(newDate.equals(oldDate)){
//            rowData[2] = "";
//        } else {
//            rowData[2] = newDate;
//            oldDate = newDate;
//        }
        
        if(theLedger.get(i).getType().equals("4")){
            rowData[3] = theLedger.get(i).getCategory(); 
            rowData[2] = "";
        }else {
            rowData[2] = theLedger.get(i).getCategory();
            rowData[3] = "";
        }
        rowData[4] = theLedger.get(i).getAmount();
        rowData[5] = theLedger.get(i).getBalance();
        
        printModel.addRow(rowData); 
      }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrinter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrinter = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnPrinter.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnPrinter.setText("print me");
        btnPrinter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrinterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel1.setText(" . print a copy, put it in your pocket, and reveal in your moral superiority");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrinter)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrinter)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));

        tblPrinter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                ".", "date", "description", "budget", "amount", "balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPrinter);
        if (tblPrinter.getColumnModel().getColumnCount() > 0) {
            tblPrinter.getColumnModel().getColumn(0).setMinWidth(15);
            tblPrinter.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblPrinter.getColumnModel().getColumn(1).setMinWidth(25);
            tblPrinter.getColumnModel().getColumn(1).setPreferredWidth(25);
            tblPrinter.getColumnModel().getColumn(2).setMinWidth(70);
            tblPrinter.getColumnModel().getColumn(2).setPreferredWidth(70);
            tblPrinter.getColumnModel().getColumn(3).setMinWidth(70);
            tblPrinter.getColumnModel().getColumn(3).setPreferredWidth(70);
            tblPrinter.getColumnModel().getColumn(4).setMinWidth(40);
            tblPrinter.getColumnModel().getColumn(4).setPreferredWidth(40);
            tblPrinter.getColumnModel().getColumn(5).setMinWidth(40);
            tblPrinter.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnPrinterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrinterActionPerformed
        
        
    }//GEN-LAST:event_btnPrinterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintSummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintSummary().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrinter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrinter;
    // End of variables declaration//GEN-END:variables
}
